"""post description and profile image

Revision ID: 729fa3d7d786
Revises: 93aa2b26dfb7
Create Date: 2023-12-21 19:38:31.714933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729fa3d7d786'
down_revision = '93aa2b26dfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_path')
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###
