"""slug and author in Post table

Revision ID: 93aa2b26dfb7
Revises: d4df6dd8619d
Create Date: 2023-12-18 22:05:31.453026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93aa2b26dfb7'
down_revision = 'd4df6dd8619d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###
