"""relationship corections

Revision ID: d4df6dd8619d
Revises: fe15104a2765
Create Date: 2023-12-17 15:47:47.163716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4df6dd8619d'
down_revision = 'fe15104a2765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
